-- -------------------------------------------------------------
-- 
-- File Name: HDL_files/modem.vhd
-- Created: 2021-06-02 20:44:45
-- 
-- Generated by MATLAB 9.7 and HDL Coder 3.15
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 10
-- Target subsystem base rate: 10
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: copy
-- Source Path: copy
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY copy IS
END copy;


ARCHITECTURE rtl OF copy IS

BEGIN
  -- Baseband Receiver
  -- 
  -- Modem Design 6LoWPAN
  -- 
  -- Baseband Transmitter

END rtl;

